### ISSUE TITLE
UI Design for the end to end tool

### ISSUE THREAD

**Issue by Shivamdhar** [agatekartik/PredEsca#10]
To put the end to end workflow in a neat way, suggestions for a dashboard are required. It also includes additional features that Soumya was talking about.

**Comment by agatekartik** [comment]
For now, keep the UI simple:

- Create a simple web page that allows user to input learning data - I reckon, as of now, this shall be CSV
- Another box for the set of incidents that shall be both, used for learning and processed for predicting
- A button that when clicked displays results in a tabular form - try and include coloring for the states

**Comment by Shivamdhar** [comment]
So, final UI to combine the two approaches and show output as: id, actual status, predicted(as by emails), predicted(as by days to fix), predicted(on basis of merge criterion) + along with metrics.
