### ISSUE TITLE
Create a readme

### ISSUE THREAD

**Issue by agatekartik** [agatekartik/PredEsca#6]
The readme needs to have the following:

**1. Usage**
- Setup needed to run the tool (including any OS and runtime environments needed)
- Input file format and specification
- External dependencies

**2. Source code notes**
- Each source folder and code file description
- Functional breakdown of all modules
- Design description
- Algorithm overview
- APIs used
- APIs exported

**Comment by Shivamdhar** [comment]
I have added the system requirements for now. I will update the README with other details by tomorrow.
