### ISSUE TITLE
Self learning capability of the model

### ISSUE THREAD

**Issue by Shivamdhar** [agatekartik/PredEsca#9]
Very important enhancement as prediction is considered to make it more accurate.

**Comment by Shivamdhar** [comment]
Self learning capability has been introduced in the template that predicts escalation based on days_to_fix attribute.

**Comment by agatekartik** [comment]
Cool - I would like to test this before we can close this one

**Comment by Shivamdhar** [comment]
This has been done with the merged algo as well.
